id: PCF34B954
initial_creation_type: input
source_metadata:
  title: 'N훮g훮rjuna: Ratn훮val카'
  language: bo
  volumes:
    6e2f80de063448a597f77c0840e0a746:
      title: CIII_Verses 1-20
      base_file: CIII_Verses 1-20.txt
      work_id: W6D5DEE44
    14cad2472e6c4edd9bbb2d5392907b2c:
      title: CIII_Verses 21-40
      base_file: CIII_Verses 21-40.txt
      work_id: W71AEA24D
    78c447e0799e4ac7910c261dd1e23523:
      title: CIII_Verses 41-60
      base_file: CIII_Verses 41-60.txt
      work_id: WCD15CAC2
    d2be60fe6b084c03a3318ea4d2b1daa7:
      title: CIII_Verses 61-80
      base_file: CIII_Verses 61-80.txt
      work_id: W05837357
    18e2d35385df47d5a627da6c77b860a3:
      title: CIII_Verses 81-100
      base_file: CIII_Verses 81-100.txt
      work_id: W16BAE1EC
    9d4646f19dd4418c9357af7e95b35eae:
      title: CII_Verses 1-20
      base_file: CII_Verses 1-20.txt
      work_id: W88F7F8F0
    a8183c446811405c9b134f094145aa1d:
      title: CII_Verses 21-40
      base_file: CII_Verses 21-40.txt
      work_id: WFB45D4BF
    d20faf26e7374cbc8de7a455e3205210:
      title: CII_Verses 41-60
      base_file: CII_Verses 41-60.txt
      work_id: W1E80D480
    5c9b41b1150549969efc06b8597e2fca:
      title: CII_Verses 61-80
      base_file: CII_Verses 61-80.txt
      work_id: W576A99BE
    4751e31ac11d490e90f26912759e6b32:
      title: CII_Verses 81-100
      base_file: CII_Verses 81-100.txt
      work_id: W55C804C5
    c414ca126c674382bdeb2a62b3327f25:
      title: CIV_Verses 1-20
      base_file: CIV_Verses 1-20.txt
      work_id: W4F568D07
    f6d263c3cff640a1a3785b8817e557e9:
      title: CIV_Verses 21-40
      base_file: CIV_Verses 21-40.txt
      work_id: W30A23682
    c59bca9dbedf41deb2776784dea84bae:
      title: CIV_Verses 41-60
      base_file: CIV_Verses 41-60.txt
      work_id: W95E0B902
    d3e68c0f8a5a4f21818c15211a191a94:
      title: CIV_Verses 61-80
      base_file: CIV_Verses 61-80.txt
      work_id: W54064128
    0c26a628a606412db57b5ea17f4ff3a7:
      title: CIV_Verses 81-100
      base_file: CIV_Verses 81-100.txt
      work_id: W7EF2F2FD
    81082eca880a48d5a31b43e8d5066495:
      title: CI_Verses 1-20
      base_file: CI_Verses 1-20.txt
      work_id: W3D39ED1B
    c5512345430b4d48a9088d51416dcdc2:
      title: CI_Verses 21-40
      base_file: CI_Verses 21-40.txt
      work_id: WAFF1A0FA
    7ec067e5d4194c0c89c9242cc8e4e69e:
      title: CI_Verses 41-60
      base_file: CI_Verses 41-60.txt
      work_id: W809F5799
    b454cf31c7f640c8a8d3fca00aac360c:
      title: CI_Verses 61-80
      base_file: CI_Verses 61-80.txt
      work_id: W785D1527
    67ba7f7139d24f8789ee2fb6cb3819a0:
      title: CI_Verses 81-100
      base_file: CI_Verses 81-100.txt
      work_id: WF6F0099B
    56785798a6294cbeac71d141638115ac:
      title: CV_Verses 1-20
      base_file: CV_Verses 1-20.txt
      work_id: WD694D48D
    3ccb8245e5b44b1abeebdadbfdd8cd6a:
      title: CV_Verses 21-40
      base_file: CV_Verses 21-40.txt
      work_id: W0C1568A4
    2b24981cfda7452c9d4aa11cbbea2d87:
      title: CV_Verses 41-60
      base_file: CV_Verses 41-60.txt
      work_id: W26AF86B1
    4ed2d98fa26e44a1a021c935a5460cef:
      title: CV_Verses 61-80
      base_file: CV_Verses 61-80.txt
      work_id: WC2B5D885
    2cf21e43d80f441cb958095ad209358a:
      title: CV_Verses 81-100
      base_file: CV_Verses 81-100.txt
      work_id: WF180AEAA
    ab0a328c5b2e4b66a89c91eb21c69384:
      title: Colophon
      base_file: Colophon.txt
      work_id: W260E619C
    acf82f5ab00c40ac9023922ed45269b4:
      title: Preface
      base_file: Preface.txt
      work_id: WB7F57570
    c90b247629b54e178b3ec02ff618fcf4:
      title: Title
      base_file: Title.txt
      work_id: WF381FB0F
  chapter_to_tile:
    CI: Chapter 1
    CII: Chapter 2
    CIII: Chapter 3
    CIV: Chapter 4
    CV: Chapter 5
created_at: '2022-03-01T23:10:37.929648'
last_modified_at: '2022-03-01T23:10:37.929656'
